version: '2'
services:
    sandbox-app:
        image: sandbox
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sandbox-postgresql:5432/sandbox
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sandbox-postgresql:
        extends:
            file: postgresql.yml
            service: sandbox-postgresql
